# -*- coding: utf-8 -*-
"""logistic1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvPg_GGswkTR-yC4oVa3HAzJJtg4FAz0
"""

import pandas as pd
import streamlit as st
from sklearn.linear_model import LinearRegression
import pickle
from pickle import load

st.title("Model Deployment:Logistic Regression")
st.sidebar.header("User INput Parameters")

def user_input_parameters():
  cx=st.sidebar.selectbox("Gender",('1','0'))
  cr=st.sidebar.selectbox("Insurance",('1','0'))
  sa=st.sidebar.selectbox("Seatbelt",('1','0'))
  ca=st.sidebar.number_input("Insert the Age",min_value=0,max_value=120,step=1)
  la=st.sidebar.number_input("Insert the Loss",min_value=0)

  data={'CLMSEX':cx,
        'CLMINSUR':cr,
        'SEATBELT':sa,
        'CLMAGE':ca,
        'LOSS':la}
  features=pd.DataFrame(data,index=[0])
  return features
#store the user inputs in a single row dataframe
df=user_input_parameters()

st.subheader("User Input Parameters")
st.write(df)

#load model

with open("model.pkl","rb") as file:
  clf=pickle.load(file)

#predict
predictions=clf.predict(df)

prediction_proba=clf.predict_proba(df)
st.subheader("Predictied Result")
st.write('Yes' if prediction_proba[0][1]>0.5 else 'No')

st.subheader("Prediction Probability")
st.write(prediction_proba)